### ISSUE TITLE
Alertmanager:0.14.0 is not allowing arguments

### ISSUE THREAD

**Issue by vivekbny** [prometheus/alertmanager#1254]
**Deployment failed with an error "unknown short flag '-s'"?**
**However deployment is successful with Alertmanager version 0.12.0**
**Unable to deploy with v0.14.0**

**dev region**

Error: MESOS_TASK_ID=dev_xxx_monitoring_alertmanager.50dd9d17-17aa-11e8-983e-baa47a6be7d0 -p 9093:9093/tcp -p 8001:8001/tcp --name mesos-e4cfa6b5-722d-4052-8405-81840ee3bc57-S0.0df0076a-da2a-4b0e-b4b2-16a00364f8d5 prom/alertmanager:0.14.0 -storage.path /alertmanager -config.file /etc/alertmanager/config.yml -mesh.nickname r0000000c -mesh.listen-address :8001 -log.level info -mesh.peer r0000000d:8001
alertmanager: error: unknown short flag '-s', try --help

* Alertmanager version:

	V0.14.0

* Prometheus version:

	2.0

* Alertmanager configuration file:
```
  alertmanager:
    image: prom/alertmanager:0.14.0
    ports:
      - mapping: "9093:9093"
        name: alertmanager
      - mapping: "8001:8001"
        name: meshport        
    constraints:
      - [ "hostname", "CLUSTER", "localhost.aaa.net" ]

    parameters:
      - key: memory-swap
        value: "-1"
    healthChecks:
      - protocol: "HTTP"
        path: "/"
        gracePeriodSeconds: 300
        intervalSeconds: 60
        portIndex: 0
        timeoutSeconds: 20
        maxConsecutiveFailures: 3
    args:
      - "-storage.path"
      - "/alertmanager"
      - "-config.file"
      - "/etc/alertmanager/config.yml"
      - "-mesh.nickname"
      - r0000000c
      - "-mesh.listen-address"
      - ":8001"
      - "-log.level"
      - info
      - "-mesh.peer"
      - r0000000d:8001
```

* Logs: Alertmanager
```
MESOS_TASK_ID=dev_xxx_monitoring_alertmanager.50dd9d17-17aa-11e8-983e-baa47a6be7d0 -p 9093:9093/tcp -p 8001:8001/tcp --name mesos-e4cfa6b5-722d-4052-8405-81840ee3bc57-S0.0df0076a-da2a-4b0e-b4b2-16a00364f8d5 prom/alertmanager:0.14.0 -storage.path /alertmanager -config.file /etc/alertmanager/config.yml -mesh.nickname r0000000c -mesh.listen-address :8001 -log.level info -mesh.peer r0000000d:8001
alertmanager: error: unknown short flag '-s', try --help
```

**Comment by roidelapluie** [comment]
Hello

Alertmanager has switched kingpin for its CLI.

Arguments take `--` instead of `-`.

**Comment by vivekbny** [comment]
Thanks a lot, it worked.

**Comment by camsjams** [comment]
Kind of a big change to throw in there without changing the version number accordingly

**Comment by camsjams** [comment]
True and fair. Easy fix on my side, and thank you for you hard work.

**Comment by sethubala76** [comment]
eshan@eshan-Lenovo-ideapad-310-15ISK:/docker/prometheus$ docker run -it -d --name prometheus -p 9090:9090 -v /docker/prometheus:/etc/prometheus --link alertmanager prom/prometheus --config.file=/etc/prometheus/prometheus.yml -alertmanager.url="http://alertmanager:9093/"
abb4a243ebb6bda231c1e9c4a0d1d3a8ecc216531abd07ac555354c1b289b9f9
eshan@eshan-Lenovo-ideapad-310-15ISK:/docker/prometheus$ docker logs prometheus
Error parsing commandline arguments: unknown short flag '-a'
prometheus: error: unknown short flag '-a'

**Comment by hoffie** [comment]
@sethubala76

`-alertmanager.url` should probably be `--alertmanager.url` instead. Usually, you should ask such questions on the mailing list or on IRC. Github is mainly used for bug reports.

**Comment by rjain1328** [comment]
Hi.. I am facing one issue related to alertmanager.ym file can Anyone help me?

-----this is alertmanager.yml file...------

[root@prod-jenkins103 alertmanager]# cat alertmanager.yml 
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - 
    name: prometheus
    pagerduty_configs:
      - 
        http_config:
          proxy_url: "http://pkg.proxy.prod.jp.local:10080"
        routing_key: b2949a1fb1f34fd2850d49ef4d5f262e


--------

The error I am getting is this---
● alertmanager.service - AlertManager Server Service
   Loaded: loaded (/etc/systemd/system/alertmanager.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2019-11-19 20:20:16 JST; 2s ago
  Process: 44411 ExecStart=/usr/local/bin/alertmanager --config.file /etc/alertmanager/alertmanager.yml --storage.tsdb.path /var/lib/alertmanager (code=exited, status=1/FAILURE)
 Main PID: 44411 (code=exited, status=1/FAILURE)

Nov 19 20:20:16 prod-jenkins103.dsd.prod.rsc.local systemd[1]: Started AlertManager Server Service.
Nov 19 20:20:16 prod-jenkins103.dsd.prod.rsc.local systemd[1]: Starting AlertManager Server Service...
Nov 19 20:20:16 prod-jenkins103.dsd.prod.rsc.local alertmanager[44411]: alertmanager: error: unknown long flag '--storage.tsdb.path', try --help
Nov 19 20:20:16 prod-jenkins103.dsd.prod.rsc.local systemd[1]: alertmanager.service: main process exited, code=exited, status=1/FAILURE
Nov 19 20:20:16 prod-jenkins103.dsd.prod.rsc.local systemd[1]: Unit alertmanager.service entered failed state.
Nov 19 20:20:16 prod-jenkins103.dsd.prod.rsc.local systemd[1]: alertmanager.service failed.

---

**Comment by Bobalou622** [comment]
I had the same issue.
I managed to resolve the issue.... " alertmanager: error: unknown long flag '--storage.tsdb.path', try --help" by... 

updating the "--storage.tsdb.path" argument in the alertmanager service to "--storage.path="PATH"
