### ISSUE TITLE
silenced and inhibited filters for listAlerts endpoint don't work

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#1359]
**What did you do?**

Attempted to list only inhibited or only silenced alerts from the api:

http://alertmanager.url.biz/api/v1/alerts?silenced=false&inhibited=true
http://alertmanager.url.biz/api/v1/alerts?silenced=true&inhibited=false

**What did you expect to see?**
Only inhibited or silenced alerts
**What did you see instead? Under which circumstances?**
`inhibited=true`: Active, inhibited, and unprocessed alerts
`silenced=true`: Active, silenced, and unprocessed alerts

* Alertmanager version: current master

**Comment by simonpasquier** [comment]
If I were asked before your report, I wouldn't have been surprised by the current behavior. Maybe it is worth adding more filters to the endpoint in order to cover all possible use cases?

Only silenced alerts
http://localhost:9093/api/v1/alerts?silenced=true&inhibited=false&active=false&unprocessed=false

Only active alerts
http://localhost:9093/api/v1/alerts?silenced=false&inhibited=false&active=true&unprocessed=false

By default, boolean values would be `true` to stick with the actual situation.

**Comment by stuartnelson3** [comment]
yeah, I suppose we should account for all situations.

wish we didn't have to have an ever growing list of querystring vars, but I don't think it's very user-friendly to use a bitmask ..
