### ISSUE TITLE
go get api error on v0.50.1

### ISSUE THREAD

**Issue by shameertt** [prometheus/alertmanager#1574]
when am trying to run this "go get github.com/prometheus/alertmanager/api" i got this message 
can't load package: package github.com/prometheus/alertmanager/api: no Go files in /home/my_name/go/src/github.com/prometheus/alertmanager/api. How to resolve this?

**Comment by mxinden** [comment]
Can you give us some more details? What are you trying to achieve?

**Comment by shameertt** [comment]
am trying to run v0.50.01 version, i got an error on api pakage importing stmt.

**Comment by juliusv** [comment]
@shameertt `github.com/prometheus/alertmanager/api` is indeed not a Go package, as it does not contain any Go files. The directory contains packages though. Those should both work:

- `go get github.com/prometheus/alertmanager/api/v1`
- `go get github.com/prometheus/alertmanager/api/v2`

Or get both of them: `go get github.com/prometheus/alertmanager/api/...`

Closing, as this seems to be solved. Please address usage questions to the IRC channel or mailing list rather than GitHub issues though: https://prometheus.io/community/
