### ISSUE TITLE
Support notification for Typetalk?

### ISSUE THREAD

**Issue by is2ei** [prometheus/alertmanager#1669]
Hi,
It looks alertmanager supports notification for some chat apps (i.e. Slack). How about supporting [Typetalk](https://www.typetalk.com/) too? If this suggestion is acceptable, I'd like to create PR.

**Comment by stuartnelson3** [comment]
Hey @is2ei , thanks for writing! We're currently not accepting additional notification integrations, since we are a small team and would not be able to properly maintain the new integration.

If this is something your team needs, you can write a webhook receiver that accepts the notification from alertmanager, and then forwards it to Typetalk: https://prometheus.io/docs/alerting/configuration/#%3Cwebhook_config%3E

**Comment by is2ei** [comment]
@stuartnelson3 Thanks for your reply! I will  close this issue

**Comment by mxinden** [comment]
In case you are building the webhook for typetalk @is2ei, I am sure the community would appreciate it to be open sourced and referenced here.
