### ISSUE TITLE
Silence match on value

### ISSUE THREAD

**Issue by alastrange** [prometheus/alertmanager#1691]
It would be useful for a silence to be able to match on the evaluated value of an alert.  For example, if we have an alert triggered by a count, we wish to silence the alert for only that number -- any increase in the count should negate the silence.

Prometheus alerts expose the evaluated value with the $value variable, but it does not seem to be communicated to AlertManager.  I tried to do this by adding a custom label to the alert:

labels:
   value: "{{ $value }}"

but this seems to only ever be evaluated on the first occurrence of the alert.  So if the alert was triggered with a count of 15, that is the value of the label even if the number increases.

Is there a feature that can be added or another strategy to support matching on value like this?  thanks

**Comment by brian-brazil** [comment]
See https://www.robustperception.io/dont-put-the-value-in-alert-labels

Anything that predicates alerts on their value would have to be done in Prometheus, and I don't see any way this would be practical.

**Comment by roidelapluie** [comment]
You can use count_values() if you really want.

**Comment by MitchelNijdam-Rockstars** [comment]
Let me put out a use case where I could see value in this:

We are alerting when the number of incidents is > 0. Imagine we get an alert that there are 4 incidents. We identify the issues, and since it takes some time to solve them, we want to silence the alert for a while. But only for those 4 incidents. If suddenly there are more incidents, we need to get alerted again since there are new problems.

It would be great if I could create a silence saying:

"Silence alert X for Y time when the value is 4 or lower"

I don't really see how this can be solved in the Prometheus rules, as the "identified problems" counter is a flexible, constantly changing value.

**Comment by siegenthalerroger** [comment]
I completely agree that this has a raison-d'etre and can't be solved using prometheus rules. @MitchelNijdam-Rockstars precisely explained my thoughts precisely, sometimes you just want the Alert to be silenced because you know of the X number of failures, but if that increases it is relevant to be alerted again.

@stuartnelson3 are we overseeing some feature in Prometheus or AlertManager that solves this?
