### ISSUE TITLE
Alertmanager and NTLM

### ISSUE THREAD

**Issue by jdamata** [prometheus/alertmanager#1777]
**What did you do?**
Deployed alertmanager:v0.16.1

**What did you expect to see?**
Emails would be able to send.

**What did you see instead? Under which circumstances?**

With alertmanager v0.16.1 I see errors:

```
level=error ts=2019-02-28T18:37:06.953152843Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="unknown auth mechanism: NTLM"
level=error ts=2019-02-28T18:37:06.95320284Z caller=dispatch.go:177 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="unknown auth mechanism: NTLM"
```

with alertmanager v0.15.2 no errors are present and emails are able to send.

I understand that alertmanager won't support ntlm authentication because its supported in the standard go library. Whats concerning to me is that an older version of alertmanager is working.

**Comment by hoffie** [comment]
Could it be that you are hitting #1721? In other words, your mail server may support NTLM, but previously alertmanager would send mail without AUTHenticating at all while it would now fail due to the above mentioned change in behaviour.

You could try the pull request #1739 to see if it fixes your issue as well.

**Comment by jdamata** [comment]
@hoffie This is exactly my problem. Thanks. Ill wait for (1739)[https://github.com/prometheus/alertmanager/pull/1739] to get merged in and released.
