### ISSUE TITLE
Alert Manager SSL support

### ISSUE THREAD

**Issue by ackarande** [prometheus/alertmanager#1807]
I don't see Alert Manager explicitly supporting SSL. Suggested approach is using a reverse proxy.
I think Alert Manager should natively provide such feature. Please suggest.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
