### ISSUE TITLE
How can I set alerts to different levels,such as warning\error\critical.....

### ISSUE THREAD

**Issue by koupeng** [prometheus/alertmanager#1842]
**What did you do?**
How can I set alerts to different levels,such as warning\error\critical.....

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
