### ISSUE TITLE
Alertmanager  send two or more resolved to my mail.

### ISSUE THREAD

**Issue by gjpei2** [prometheus/alertmanager#1845]
hello
i meet a problem in my prometheus cluster
i have two alertmanager ,they make a HA ,and i have two prometheus with the same 
configuration.when a alert resloved ,in my understanding ,one alert should have one resloved,but in fact ,sometimes ,i received two or more resloved . my configuration as follow,please don't care my poor english

prometheus configuration:
global:
      scrape_interval:     15s
      evaluation_interval: 15s

alertmanager configuration:
route:
      group_by: ['alertname','cluster','service','instance']
      group_wait: 60s
      group_interval: 5m
      repeat_interval: 3h
      receiver: gjpei
      routes:
      - receiver: 'k8s_2s'
        group_interval: 5m
        match:
          severity: page
and my rule is like  :
- name: 2s_pod_restart_monitor
      rules:
      - alert: Aiaas_PodRestart
        expr: changes(kube_pod_container_status_restarts_total{namespace="default"}[5m])>0
        for: 25s
        labels:
          severity: k8s_2s
        annotations:
          summary: "pod {{$labels.pod}} is restarting，value is {{ $value }}！"

**Comment by gjpei2** [comment]
I tried many ways to solve the problem,increase group wait ,increase group interval,and y lowering the --rules.alert.resend-delay to 5s ,lowering for time in my rule ,it is all  no help to me

**Comment by stuartnelson3** [comment]
I recommend reading [this issue](https://github.com/prometheus/alertmanager/issues/1550), and if that doesn't solve your issue, send an email to the prometheus mailing list prometheus-users@googlegroups.com for support. This is a request for help rather than a bug report or feature request, which is more suited to the mailing list, where your question will reach a wider audience and be able to help more people.

**Comment by gjpei2** [comment]
i review this issue carefully,but can't resloved my questions, thanks for your reply.
