### ISSUE TITLE
Adding `active=true` in alert list not passed to backend

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#1867]
* Alertmanager version:

	current master https://github.com/prometheus/alertmanager/commit/f32ad1dd8b0367100f8f0abcd121ce743711a549

When trying to filter the alert groups main view to only display silenced and/or inhibited alerts, I added `&active=false` to the URL:

`http://localhost:9093/#/alerts?silenced=false&inhibited=true&active=false`

What got sent to the backend was:

`http://localhost:9093/api/v2/alerts/groups?silenced=false&inhibited=true`

the param `active` is default true, so I am unable through the webui to see anything else.

**Comment by wbh1** [comment]
I'd like to take this on if that's alright. I think I've already got most of it implemented.

**Comment by stuartnelson3** [comment]
Definitely! Let me know if I can help. It should only require changes to the elm code.

**Comment by wbh1** [comment]
I've gotten the filter working. Should there be a checkbox for active since it's a default filter like inhibited and silenced? Or do you think it is safe to assume that most people will be fine with the default behavior and anyone who isn't should probably know how change URL query params?

![Screen Shot 2019-05-07 at 6 03 44 PM](https://user-images.githubusercontent.com/11506822/57336052-9c687a00-70f2-11e9-8f2e-a5e97b9d21ff.png)

**Comment by stuartnelson3** [comment]
Let's start with the default behavior + supporting the URL param, and we can think about adding the checkbox. Maybe we can think of a better way to support selecting the desired state through the UI, for a different PR.
