### ISSUE TITLE
Feature Request: Notify with custom messages

### ISSUE THREAD

**Issue by jbchen120** [prometheus/alertmanager#1896]
Currently, alertmanager has an option that can be configured to send a notification when an alert is resolved. Was wondering if an additional feature was possible to send a notification when all alerts are resolved. It appears that the current structure of the Notifier interface does not allow for this, because it only appears to notify on currently existing alerts rather than allow for sending separate messages apart from alerts.

It seems like the current implementation of the notifier sends the "alert resolved" message in the form of an Alert, but the desired notification that would be sent when all firing alerts are resolved will not be an Alert (rather, simply just a message). One idea would be to change the Notifier interface to add another method that allows sending notifications as simple messages rather than as alerts. This could be used not only for sending notifications when all alerts are resolved, but also for other notifications that are separate from the normal alerts.

I can take up this task if it sounds like a good idea; I already have something in the works.

**Comment by brian-brazil** [comment]
There are only notifications, and no matter their composition in terms of firing and resolved alerts their behaviour is always the same. If you want to do something more complex, I'd suggest looking at the webhook notifier.

**Comment by peragwin** [comment]
The idea we had here was originally to use something like the webhook API to post to another application which would track for us how many alerts are currently active. This external service would then post somewhere to alert us when there are no more alerts active.

But we thought it might make more sense just to include such a feature in alertmanager itself, and this is probably the route we're going to take in order to not have to maintain another deployment. @jbchen120 will be likely posting a pull request, so we're looking for feedback or suggestions on the feature itself in case others want to use it.

**Comment by roidelapluie** [comment]
You can already do this with the mail/slack/templates.

**Comment by stuartnelson3** [comment]
Having a webhook service that keeps track of firing alerts is probably the easiest way to go, since that could then send your message.

**Comment by simonpasquier** [comment]
I don't think we want to complicate the AlertManager's workflow. As others said, the webhook integration is the way to go IMHO.

**Comment by simonpasquier** [comment]
Closing for now as no maintainer felt that it should be part of AlertManager itself. If you happen to implement something as an external service, you're welcome to share the information on the [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users). Thanks!
