### ISSUE TITLE
Sending Alert emails using Jenkins webhook

### ISSUE THREAD

**Issue by vivekj11** [prometheus/alertmanager#1900]
Apologies for creating an issue rather it should be a requirement or knowledge gathering.

I have my Alertmanager up and running and I can see all active alerts on alertmanager dashboard. 
Now I want an email notification for alerts based on created rules.
-> I tried getting internal smtp details but seems like its a very hectic task in organizational env.
-> For other small tasks, we use Jenkins webhook to send an email notification to our org email address and it works.
-> I assume there is something I can do to integrate alertmanager with Jenkins and send alerts to my email address, but not completely sure how to do that.
I was wondering If someone can redirect me to a relevant post or a brief HowTo to achieve this model. 
thanks in advance.

**Comment by simonpasquier** [comment]
I did a quick search but couldn't find any 3rd integration between AlertManager and Jenkins. As this is a support question rather than an issue report, I'm closing it for now. Feel free to use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by roidelapluie** [comment]
We have that integrated:

https://github.com/roidelapluie/alert2amqp
https://github.com/roidelapluie/amqp2jenkins

simili docs:
https://www.slideshare.net/roidelapluie/incident-resolution-as-code
