### ISSUE TITLE
Using auth in receivers

### ISSUE THREAD

**Issue by krakazyabra** [prometheus/alertmanager#2001]
Hi everybody!  
I'm just wondering, can i provide auth credentials in receivers config to use then with webhook? something similar to header in curl. My target url requires auth (ID and token, like `curl -H "Authentication: ID TOKEN"`), but i can't use them in link.

**Comment by mxinden** [comment]
Are you looking for this: https://prometheus.io/docs/alerting/configuration/#http_config ?

**Comment by krakazyabra** [comment]
Hi, @mxinden. Thank you for reply. 
is  
```
basic_auth:
  username: ID_here
  password: TOKEN_here
```
the same as `curl -H "Authentication: ID TOKEN"`?
Thank you.

**Comment by simonpasquier** [comment]
@krakazyabra this change wouldn't be limited to AlertManager and it has been discussed before: see https://github.com/prometheus/common/issues/140. The conclusion has been that we don't want to support arbitrary authentication schemes.

**Comment by ikarlashov** [comment]
> The conclusion has been that we don't want to support arbitrary authentication schemes.

Why? I'm trying to hook up alertmanager with splunk and since Splunk is demanding `Splunk` to be placed in `Authorization` header - I can't use alertmanager.

**Comment by roidelapluie** [comment]
I think that it is exactly the reason. There are thousands of products out there, we can't support non standard authentication schemes for all of them. In the case of splunk from what I understand they invented a completely new scheme?

**Comment by ikarlashov** [comment]
@roidelapluie 

I don't know what is underneath in each auth scheme, but in case of splunk you just need to put:

`Authorization: Splunk TOKEN`

And from my perspective changing Bearer to Splunk in header is just a matter of couple lines of code :)

**Comment by f4nha** [comment]
@ikarlashov we are having the same issues here to integrate with Splunk, did you find any workaround for this?

**Comment by nberkley** [comment]
> I think that it is exactly the reason. There are thousands of products out there, we can't support non standard authentication schemes for all of them. In the case of splunk from what I understand they invented a completely new scheme?

This seems to more or less be the justification every time something like this comes up, but the majority of these I've seen seem to boil down to "let me set arbitrary headers in http_config" which seems like a very small change to allow alertmanager to talk to almost anything. Heck, you could scrap the entire bearer_token and basic_auth sections without any loss of functionality if you just supported setting arbitrary headers.

The current state means that you basically always end up writing a custom authentication server to translate from what alertmanager will provide to whatever format the thing you're talking to supports. Which is really not great and creates ample opportunity to create new security problems for yourself.

Am I missing some reason to be so opinionated about specifying bearer token/basic auth credentials rather than just making all headers (including the Authorization header) configurable?

**Comment by roidelapluie** [comment]
This is supporter in alertmanager 0.22, currently in release candidate.

e.g.:

```
authorization:
  credentials: password
  type: Splunk
```
