### ISSUE TITLE
email line length limit

### ISSUE THREAD

**Issue by alburthoffman** [prometheus/alertmanager#2068]
**What did you do?**
html emails sent from alert manager hit line length limit in https://tools.ietf.org/html/rfc2822#section-2.1.1.

This cause clients get broken html emails. Some links are broken because of extra bang + newline feed.

**What did you expect to see?**
user can get a raw html emal

**What did you see instead? Under which circumstances?**
html emails sent from alert manager hit line length limit in https://tools.ietf.org/html/rfc2822#section-2.1.1.

This cause clients get broken html emails. Some links are broken because of extra bang + newline feed.

**Environment**

* System information:

	linux

* Alertmanager version:

	0.15.2

* Prometheus version:

	2.13.0

**Comment by simonpasquier** [comment]
It is already fixed by https://github.com/prometheus/alertmanager/pull/1609, please update to a more recent version of Alertmanager. 

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by alburthoffman** [comment]
thx. it helps
