### ISSUE TITLE
How to send alert to another people when problem was'nt solved 

### ISSUE THREAD

**Issue by 19CMkudo** [prometheus/alertmanager#2080]
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

	insert output of `alertmanager --version` here

* Prometheus version:

	insert output of `prometheus -version` here (if relevant to the issue)

* Alertmanager configuration file:
```
insert configuration here
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by simonpasquier** [comment]
I'm closing it for now since it looks more like a support question than a bug report or feature request.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
