### ISSUE TITLE
Alertmanager 422 response code doesn't show reason

### ISSUE THREAD

**Issue by ffahri** [prometheus/alertmanager#2088]
Such as Opsgenie integration. 
If you set wrong or not applicable string in field of Opsgenie. Thats just show 
priority: P4
```
alertmanager level=error ts=2019-11-01T07:30:15.047Z caller=notify.go:367 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"opsgenie\" due to unrecoverable error: unexpected status code 422"                    
alertmanager level=error ts=2019-11-01T07:30:15.047Z caller=dispatch.go:264 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"opsgenie\" due to unrecoverable error: unexpected status code  ││ 422"
``` 
https://github.com/prometheus/alertmanager/blob/94d875f1227b29abece661db1a68c001122d1da5/notify/notify.go#L367

Opsgenie returns response body when this cases. This is useful if you try to send alert and get 422 but don't know what is wrong
```
{"message":"Request body is not processable. Please check the errors.","errors":"priority":"should be one of [ P1, P2, P3, P4, P5 ]"}

```

**Comment by simonpasquier** [comment]
This is fixed with the latest Alertmanager release. Here is what I get from my side:

```
level=error ts=2019-11-04T08:43:57.082Z caller=dispatch.go:266 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"opsgenie\" due to unrecoverable error: unexpected status code 422: {\"message\":\"Request body is not processable. Please check the errors.\",\"errors\":{\"priority\":\"should be one of [ P1, P2, P3, P4, P5 ]\"},\"took\":0.001,\"requestId\":\"e08b61f2-cff3-4704-9ddf-33cf12258d47\"}"
```

**Comment by romenyrr** [comment]
For some reason, I'm getting this error even though I'm passing through a correct "P" value through my notification template.

`{{ define "opsgenie.myorg.priority"}} 
	{{ range .Alerts }}
		{{ if eq .Labels.severity "critical"}}
			P1
		{{ else }}
			P3
		{{ end }} 
	{{ end }}
{{ end }}`

Is my block defined incorrectly? 

error message: 
`level=error ts=2020-01-03T05:36:34.129Z caller=dispatch.go:301 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"opsgenie\" due to unrecoverable error: unexpected status code 422: {\"message\":\"Request body is not processable. Please check the errors.\",\"errors\":{\"priority\":\"should be one of [ P1, P2, P3, P4, P5 ]\"},\"took\":0.001,\"requestId\":\"c4589a15-34e6-4530-8dde-d45f3557f6f4\"}"`

**Comment by simonpasquier** [comment]
@romenyrr if you have more that one alert then the value can be `P1P1P3...`

**Comment by devopskid** [comment]
> @romenyrr if you have more that one alert then the value can be `P1P1P3...`

is there a solution for this scenario? how do we make multiple alerts not concatenate the P value into one big string?

**Comment by OlleLarsson** [comment]
> > @romenyrr if you have more that one alert then the value can be `P1P1P3...`
> 
> is there a solution for this scenario? how do we make multiple alerts not concatenate the P value into one big string?

The solution is to group the alerts by severity.
Here's a draft that you should be able to draw inspiration from:
```
  config:
    route:
      group_by: [severity]
    routes:
    - receivers:
       - name: opsgenie
         opsgenie_configs:
         - priority: {{ if eq .GroupLabels.severity "critical"}}P1{{else if eq .GroupLabels.severity "warning"}}P2{{else}}P3{{end}}
```

**Comment by larsgerber** [comment]
> For some reason, I'm getting this error even though I'm passing through a correct "P" value through my notification template.
> 
> > {{ define "opsgenie.myorg.priority"}}
> > {{ range .Alerts }}
> > {{ if eq .Labels.severity "critical"}}
> > P1
> > {{ else }}
> > P3
> > {{ end }}
> > {{ end }}
> > {{ end }}
> 
> Is my block defined incorrectly?
> 
> error message: `level=error ts=2020-01-03T05:36:34.129Z caller=dispatch.go:301 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"opsgenie\" due to unrecoverable error: unexpected status code 422: {\"message\":\"Request body is not processable. Please check the errors.\",\"errors\":{\"priority\":\"should be one of [ P1, P2, P3, P4, P5 ]\"},\"took\":0.001,\"requestId\":\"c4589a15-34e6-4530-8dde-d45f3557f6f4\"}"`

Hello @obthearchitect 

I had the same issue today. In the beginning, I had everything on one line, which worked. Then I tried to spread the template on multiple lines for better readability. After that change, it stopped working.

After consulting the Go Template documentation, I found out that the line break is added to the string. That's why OpsGenie rejected it.

Here I found an example that worked: https://hodovi.cc/blog/creating-awesome-alertmanager-templates-for-slack/

My template now looks like this.
```
{{ define "opsgenie.jira.priority" -}}
{{- if eq .GroupLabels.severity "critical" -}}
P1
{{- else if eq .GroupLabels.severity "warning" -}}
P2
{{- else if eq .GroupLabels.severity "info" -}}
P3
{{- else -}}
P4
{{- end }}
{{- end }}
