### ISSUE TITLE
Allow  repeating SILENCES

### ISSUE THREAD

**Issue by f0** [prometheus/alertmanager#214]
with repeating silences you can define a silence for a backup window e.g every day from 01:00 till 02:00 , atm you need to create many many silences....

**Comment by fabxc** [comment]
That doesn't sound right. There's a fair amount of risk that silences and backups get out of sync at some point. It's more appropriate to let your backup-script schedule a silence. This needs documentation of the silence API, of course.

**Comment by f0** [comment]
@fabxc yes thats also an option

**Comment by brian-brazil** [comment]
Even better, the alert shouldn't happen when a backup is in progress.

**Comment by f0** [comment]
@brian-brazil  yes this would be the best option, but i think its not always possible

**Comment by brian-brazil** [comment]
Having the backup script create/delete silences is the appropriate fallback then.

**Comment by fabxc** [comment]
That may be achievable/feasible for some alerts. One could have that state in a metric and disable alerts by that, but that seems like significant noise compared to scheduling a silence.

**Comment by brian-brazil** [comment]
If you have alerts firing due to backups, your alerting strategy may have room for improvement.

The type of alert that fires during a backup is usually either a single machine being down or slow, which is not a service-level issue and thus not page worthy. Only if there's a service-level issue or a machine is down for much longer than a backup takes should it notify the oncall.

It's generally better to have your alerting setup such that it doesn't require messing around with silences for routine operational events.

**Comment by fabxc** [comment]
Totally agree that this is the ideal case.

**Comment by f0** [comment]
@brian-brazil  agree , but the world is not ideal, you have single instance systems and Oracle databases and and and.....

**Comment by brian-brazil** [comment]
Indeed.

It doesn't look like there's anything to do here on the Prometheus side, having the script create and delete silences is the recommended approach.

**Comment by jaredstehler** [comment]
What about for an environment with a relaxed SLA (e.g. Dev)? Makes sense to only alert during business hours.

**Comment by nelsonstudent** [comment]
Guys, I've been searching and found this article. I think it adds to the conversation.

https://awesome-prometheus-alerts.grep.to/sleep-peacefully.html
