### ISSUE TITLE
How to get metric name in Alertmanager ,not only alertname?

### ISSUE THREAD

**Issue by koupeng** [prometheus/alertmanager#2171]
**What did you do?**

How to get metric name in Alertmanager ,not only alertname?

**What did you expect to see?**

get metric name in Alertmanager ,not only alertname.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
