### ISSUE TITLE
feature request: support store of webhook

### ISSUE THREAD

**Issue by zgfh** [prometheus/alertmanager#2255]
**What did you do?**
for now, alertmanager store alert in memory
should we support webhook store for someone want save alert in db or es?

**Comment by paulfantom** [comment]
I think this is possible now. You can configure alertmaneger to send alerts to a webhook receiver and persist them in some DB. For example, by using https://github.com/b-com-software-basis/alertmanager2gelf you can persist alerts in greylog2.

**Comment by roidelapluie** [comment]
A list of such integrations is at:

https://prometheus.io/docs/operating/integrations/

There are also receivers for elasticsearch in the wild.

**Comment by roidelapluie** [comment]
I close this issue here, hoping that we answered your query.

If you want for information or have more questions, feel free to reach the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by zgfh** [comment]
@roidelapluie @paulfantom thanks a lot
