### ISSUE TITLE
I not able to start alertmanager 

### ISSUE THREAD

**Issue by saaiprakash1** [prometheus/alertmanager#2266]
![image](https://user-images.githubusercontent.com/45836788/82724437-def7f700-9cf3-11ea-8674-9d5ada132945.png)

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
