### ISSUE TITLE
How to do routing specific to a service

### ISSUE THREAD

**Issue by vikrant82** [prometheus/alertmanager#2278]
This may be a basic use case but I couldn't figure out based on the documentation I looked at. 

I am expecting each of my service to create some service level alerts and package them as part of their helm charts which seems simple enough to do - each service creates a Prometheus rule for alerts it cares about.

Is it possible for the service to allow implementing some of the routing rules as part of its deployment definition ? To me it seems like there is one config file where alert manager picks the routing information from. How can individual services update that config file (a secret in k8s) as part of their deployment ?

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
