### ISSUE TITLE
alert resolved question

### ISSUE THREAD

**Issue by frankcgq105** [prometheus/alertmanager#2312]
**What did you do?**

set up an alertingr rule ,for example:

- name: defaultInstances
  rules:
  - record: job_instance_default:defaultinstances
    expr: device_status:oms:1m
  - alert: somethingwrong
    expr: job_instance_default:defaultinstances==0
    for: 1m

**What did you expect to see?**

when the device is error I can receive the alert as expect.The alertingrule operates well.
now it is good

**What did you see instead? Under which circumstances?**

But when the device shutdown,and the "device_status:oms:1m" metric value is changed into nodata

Then the alert resolved later

But I am confused,why did it sent the resolved message?what about the reason?

**Environment**

* Alertmanager version:

version 0.20.0

* Prometheus version:

	version 2.18.1

```

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
