### ISSUE TITLE
How to group alerts by a label AND status? (I want group_by: [alertstatus, alertname])

### ISSUE THREAD

**Issue by Drugoy** [prometheus/alertmanager#2333]
Currently Alertmanager groups all firing and resolved alerts if config like
```
group_by:
  - alertname
```
is used.

I'd like to be able to receive separate notifications about alerts based on both alertname and alert's status.

Maybe I can already do so, but docs don't mention built-in labels, maybe there's already something like 'status' for alerts statuses?

**Comment by Drugoy** [comment]
<a href="https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/">Here</a> I found about `alertstate`, but it doesn't seem to work.
Also, relevant ticket is #371

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by Drugoy** [comment]
Would you like me to file a new ticket rephrased as 'Add a way to separate alerts based on alerts state'?

**Comment by Drugoy** [comment]
@roidelapluie thank for your suggestion, filed a new ticket.
