### ISSUE TITLE
address XXXX: missing port in address - alertmanager v0.21.0

### ISSUE THREAD

**Issue by raz08** [prometheus/alertmanager#2338]
level=error ts=2020-07-31T14:58:49.625Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="address XXXX: missing port in address"

Any idea? verified with both latest prom and operator.

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
