### ISSUE TITLE
How to prevent sending resolve notification after resolve_timeout?

### ISSUE THREAD

**Issue by chaishiqi** [prometheus/alertmanager#2341]
Hello engineers,I have a problem with configuration of resolve_timeout. As it means, a notication of resolved will be send after the timeout. But actually the issue still be firing, it disturb the correct resolved notification

How can I prevent it?

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
