### ISSUE TITLE
How can I Send Individual Alert  for Different Servers on Different usage Criteria

### ISSUE THREAD

**Issue by GopiPacha1996** [prometheus/alertmanager#2343]
Hi All,

I am Using Prometheus for my Production Servers,my question is is there any way that we can configure different alerts for individual server.
for example I  have 3 Servers ,Server1 cpu usage is 20%  ,Server 2 cpu usage is 30% and Server 3 cpu usage is 90% .Now I need to get alert if server 1 is above 50% and server 2 cpu usage is above 90% and server 3 cpu usage is below 50%.is there anyway that i can create rules according my requirement for individual servers.Please help me out if anyone know how to do it.
Thanks in advance...!

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by hoffie** [comment]
You might be looking for this pattern:
https://www.robustperception.io/using-time-series-as-alert-thresholds

If you have further questions I suggest contacting the [mailing list](https://prometheus.io/community/), as Github issues are only used for handling bugs in the Prometheus projects.

**Comment by GopiPacha1996** [comment]
is there any possibility that i can mention host name on the rules.yml file on prometheus?

**Comment by GopiPacha1996** [comment]
Ok thanks for your reply

**Comment by GopiPacha1996** [comment]
> You might be looking for this pattern:
> https://www.robustperception.io/using-time-series-as-alert-thresholds
> 
> If you have further questions I suggest contacting the [mailing list](https://prometheus.io/community/), as Github issues are only used for handling bugs in the Prometheus projects

Can you help me out how can i create different groups ??
