### ISSUE TITLE
Feature request: Webhook alert to Flock

### ISSUE THREAD

**Issue by Daych** [prometheus/alertmanager#2350]
I can see the webhook to slack channel, and it have many doc on the web, so far I cant see any doc to setup the alert to Flock, do it available to use webhook_configs or slack_configs to use? or it can be added later on ?

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
