### ISSUE TITLE
recieve an alert if I have been reciveing a specific alert X times

### ISSUE THREAD

**Issue by hedeesaa** [prometheus/alertmanager#2351]
I want to receive an alert if "X time in a one day" I have been receiving a specific alert.
Is there any way or feature to do that?

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
