### ISSUE TITLE
Flowdock notifier has fallen by the wayside

### ISSUE THREAD

**Issue by mrwacky42** [prometheus/alertmanager#236]
While looking at the latest beta to prepare an upgrade, I notice that the FlowDock notifier has disappeared.

Please re-vivify.

**Comment by fabxc** [comment]
It will come back. However, I cannot give you any time guarantees right now.
If you need it I'd recommend to file a pull request. Implementation of new integrations is straightforward but way easier if done by someone actually using the system.

I didn't port everything right away since the new Alertmanager approaches various things differently. So plain copy&paste was not an option.

**Comment by t0mk** [comment]
I am not using Prometheus anymore, I will probably not do this again. Most of the old code is around here: 
https://github.com/t0mk/alertmanager/blob/master/manager/notifier.go#L338

**Comment by stuartnelson3** [comment]
We're not currently adding any notifiers, it's recommended to use the webhook integration for this.
