### ISSUE TITLE
pushover api use in the receiver

### ISSUE THREAD

**Issue by vmalhotra22** [prometheus/alertmanager#2369]
hi,

I want to use the push over api for sending the alerts via pushover tool.

I got all the details like API, token , key etc.

The only thing which I cannot place properly is the API.

- name: alert-pushover
     pushover_configs:
     - user_key: <key>
       send_resolved: true
       token: <token>
       title: Pusho-over alerts from Prometheus
       url: <supplementary URL>
       retry: 1m
       priority: -1

but where to use the POST an HTTPS request to https://api.pushover.net/1/messages.json????

appreciate any help
cheers

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
