### ISSUE TITLE
How does AM discover peers?

### ISSUE THREAD

**Issue by aclowkey** [prometheus/alertmanager#2419]
I tried figuring this out by reading the code. But without success. 
When I specify:
`--cluster.peer=alertmanager.service.consul:9094`

Will it only peer with the IP's resolving the DNS entry?
Or will it probe the network looking for other nodes on port 9094

My issue is some different clusters are merging for unknown reason..

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
