### ISSUE TITLE
AlertManager silencing is not working

### ISSUE THREAD

**Issue by arnavbose** [prometheus/alertmanager#2423]
Hi,

I have observed an issue with AlertManager recently. I am running alertmanager as a pod and it works fine. Alerts from Prometheus are reaching alertmanager and it's triggering alerts. It's silencing alerts created from the UI as well as curl command. The only issue is - suppose I am creating a silence for a particular host, which has multiple servers, the silencing works fine but 1 or 2 alerts still get spilled into the notification channel. I want to understand why this would happen. Either silence will not work at all for all servers belonging to the host, or silence would work for all the servers for that host. Why is this spilling alerts for any one or two servers for the particular host ?

Is it because too many alerts were getting generated and the high volume of alerts was breaching a specified queue size limit for silenced alerts? Please help me understand under what circumstance alertmanager would spill a few alerts even though the alerts were all silenced.

Thanks, 
Arnav

**Comment by sam-celer** [comment]
I have similar issues. Alerts are silenced and I can see them in the list of affected alerts in the UI. Yet the alerts are also in the alerts view and sent to the notification system (PagerDuty). If I edit the silence (Like adding a blank space to the description or whatever), the alerts get correctly silenced. The only matcher used in the silence is a field called client_name and it's set as a regex to the client name.
Last occurrence of this issue was last Sunday where somehow 4 alerts (Out of plenty of them) got through. The silence was started on the Saturday and valid for a week yet I can see those 4 alerts in PagerDuty
![image](https://user-images.githubusercontent.com/73531301/99691197-dc970f80-2a80-11eb-81eb-a3dd622fa385.png)
![image](https://user-images.githubusercontent.com/73531301/99691257-ede01c00-2a80-11eb-9203-4d634ced05df.png)

**Comment by arnavbose** [comment]
In my case the created silence works but partially. 

If the number of generated alerts during a maintenance window increases a lot, the active silence partially silences alerts. Meaning if 20 alerts were generated during a maintenance window, the active silence silenced 18-19 alerts, but 1-2 alerts still got spilled to the notification channel (slack). Ideally this should not happen. The silence should silence all alerts if it's working or should not silence any alerts if it's not working. There cannot be or should not be partial silence.  Has this issue been observed earlier?

**Comment by simonpasquier** [comment]
Closing in favor of #2426
