### ISSUE TITLE
labels.ParseMatcher allows unbalanced surrounding quotes

### ISSUE THREAD

**Issue by squat** [prometheus/alertmanager#2630]
**What did you do?**
Using `labels.ParseMatcher` with strings that have unbalanced surrounding `"`s results in successful parsing, e.g. `labels.ParseMatcher("foo=\"bar")`.

**What did you expect to see?**
Error due to unbalanced surrounding quotes

**What did you see instead? Under which circumstances?**
Successful parsing of quotes

**Environment**
CI for prom-label-proxy when bumping dependencies (https://app.circleci.com/pipelines/github/prometheus-community/prom-label-proxy/100/workflows/aa8e2071-9392-43b9-8471-2505fc38b54f/jobs/231)

* Alertmanager version:
v0.20.0

This seems quite clear from the logic in the `ParseMatcher` func. We strip any opening surrounding quotes (https://github.com/prometheus/alertmanager/blob/99e4a4fbae5938f4fd31b8bc90755826f650d9da/pkg/labels/parse.go#L126) and do not enforce a matching quote (after all, this case is optional https://github.com/prometheus/alertmanager/blob/99e4a4fbae5938f4fd31b8bc90755826f650d9da/pkg/labels/parse.go#L159 ).

This parsing is pretty liberal and is a breaking change with the previous logic. It's somewhat tricky: the previous parser allowed a closing quote without a starting quote whereas this one allows unbalanced quotes in either position. Is it intended? If so let's close this and I can fix the test-case in prom-label-proxy to not expect a failure. Otherwise, maybe we want to take stance on the balancing.

**Comment by bwplotka** [comment]
I am surprised we have this source code in alertmanager, not in prometheus common or something. Let me investigate if this was simply copied, and we can copy fixed version from github.com/prometheus/common or other spaces

**Comment by bwplotka** [comment]
* common does not have matchers: https://github.com/prometheus/common/blob/4240322d2138024beddb57544851d77a08afe19c/model/silence.go
* Prometheus looks like have optimized matches, but they do not have parsing logic for string: https://github.com/prometheus/prometheus/blob/39d79c3cfb86c47d6bc06a9e9317af582f1833bb/pkg/labels/matcher.go#L44

*Side question:* Should we move matchers + parsing to common?

Fix: https://github.com/prometheus/alertmanager/pull/2632

**Comment by beorn7** [comment]
If we need this matcher code anywhere else, we could move it to common, but note that this kind of "tolerant" syntax is more for UI purposes than for "proper" parsing. That's why I'm not surprised that we didn't need it anywhere else so far.

That's also why I like to call the matchers "PromQL-esque". They are not real PromQL. They are just inspired by it. They are also inspired by OpenMetrics (mostly the escaping rules, because [PromQL string literals follow Go escaping rules](https://prometheus.io/docs/prometheus/latest/querying/basics/#string-literals), which is weird for configs).
