### ISSUE TITLE
Where are the silence rules stored

### ISSUE THREAD

**Issue by CarTerr** [prometheus/alertmanager#2654]
**What did you do?**
I create silence rules via web ui

**What did you expect to see?**
after restarting the k8s pod, all rules for silences disappear. I want save silence rule

**Comment by beorn7** [comment]
The silences are stored in the directory specified as the `--storage.path` flag (`data/...` by default).

If you run a K8s pod without any persistent volume attached, Alertmanager stores the silences locally, and if you restart the pod, you get an empty local directory. So you need a persistent volume in a stateful set to keep silences across restarts.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
