### ISSUE TITLE
webhook url_file future request

### ISSUE THREAD

**Issue by dragoangel** [prometheus/alertmanager#3082]
**What did you do?**
Try to setup alertmanager via Helm chart with secrets and do not put all alertmanager configuration as a one secret

**What did you expect to see?**
I expect that webhook_config has option to point to file in same it done for slack and opsgeniue

**What did you see instead? Under which circumstances?**
No option for url_file is available

**Comment by OktarianTB** [comment]
I may be misunderstanding the context, but there might be a security issue here because the webhook notifier will not handle your `url` safely. The `url` field is defined as a simple `string`, not a `secret`. If you `url` contains a secret, then be aware that it can and will be logged. However, if you need a `url_file` because you are loading the URL dynamically or something, that that would be a valid use case. 🙂

**Comment by dragoangel** [comment]
Agreed, find the proper way to go with Bearer token

**Comment by simonpasquier** [comment]
closed by #3228 and #3223
