### ISSUE TITLE
Additional options for webhook_configs

### ISSUE THREAD

**Issue by hryamzik** [prometheus/alertmanager#324]
Can we have some additional options for the ```webhook_configs```? And just post them with json?
For example I'd like to pass phone numbers and chat IDs, some tag configuration (like display only these tags in sms), etc.

**Comment by brian-brazil** [comment]
You're asking for a fully general JSON->JSON templating system.

We suggest doing the logic you need in what's receiving the webhook, as it's not practical for us to offer the full range of functionality that users would be looking for here. You receive all the same data that the templates do.

**Comment by hryamzik** [comment]
But how can I use the same webhook with different options? Posting json read from yaml seem to be simple. You can set options for all the receivers except the webhook one.

**Comment by brian-brazil** [comment]
Have different receivers for your different webhook endpoints. All receivers have the options they need, in the case of the webhook that's only the URL to send to (we'll likely add the various http auth options at some point).

**Comment by hryamzik** [comment]
So you suggest encoding those options to the URL? That looks like a dirty workaround for me but I can definitely do this in ansible.

Why don't you like the idea of passing extra options?

**Comment by hryamzik** [comment]
OK, I have an sms receiver. I have 10 groups of users, so you suggest me starting 10 receivers with different options, right?

**Comment by brian-brazil** [comment]
Yes, or do the logic inside your custom code.

Allowing extra options is effectively asking for us to provide a Turing Complete JSON transformation language, combined with the Go templating language. That is well outside the scope of the Prometheus project, one custom Turing Complete language is quite enough.

**Comment by hryamzik** [comment]
@brian-brazil thank you, I'll close this for now and will get back to this when I'll start to implement SMS alerts.

**Comment by StianOvrevage** [comment]
I want to connect alertmanager directly with a third party webhook.

And instead of having to develop, run and manage a server just for translating between the default alertmanager JSON output and the expected JSON input from the third party, the option to template the actual alertmanger JSON object myself would do the job.

This is the request the third party expects:

curl -i -X POST -H "X-Version: 1" -H "Content-Type: application/json" \
-H "Authorization: bearer {{ apikey }} " \
-H "Accept: application/json" \
-d '{"text":"{{ message }}","to":["{{ receiver }}"]}' \
-s {{ webhook.url }}

So, if it would be possible for me to supply my own headers and my own payload to the webhook-url everything would be good!

**Comment by Rio** [comment]
I think just setting some headers for api tokens would be a nice addition.
