### ISSUE TITLE
Email fails- "getsockopt: connection timed out" source="notify.go:193""

### ISSUE THREAD

**Issue by mokshpooja** [prometheus/alertmanager#334]
Hi Guys, Based on [#327](https://github.com/prometheus/alertmanager/issues/327) I updated my config file. I am running from aws from inside proxy.
What do you think could be wrong? 

 [Error log](https://gist.github.com/mokshpooja/c7cd5df38986f49f5ef885bb2d8f4b20)

**Comment by jhaohai** [comment]
It is amazon's problem. You should open a ticket ask for removing smtp limitation

**Comment by mokshpooja** [comment]
its weird because, sending smtp through the same instance worked before for me. But I was using another client then Alert manager.

**Comment by jhaohai** [comment]
https://aws.amazon.com/forms/ec2-email-limit-rdns-request


原始邮件
发件人:mokshpoojanotifications@github.com
收件人:prometheus/alertmanageralertmanager@noreply.github.com
抄送:蒋浩海jhaohai@foxmail.com; Commentcomment@noreply.github.com
发送时间:2016年4月28日(周四) 21:30
主题:Re: [prometheus/alertmanager] Email fails- "getsockopt: connectiontimed out" source="notify.go:193"" (#334)


its weird because, sending smtp through the same instance worked before for me. But I was using another client then Alert manager.
