### ISSUE TITLE
Flaky test: TestClusterJoinAndReconnect/TestTLSConnection

### ISSUE THREAD

**Issue by alexweav** [prometheus/alertmanager#3593]
**What did you do?**

This test has failed on the CI intermittently a couple of times in roughly 10 builds, on changes that seem unrelated.

Example of an affected build:
https://github.com/prometheus/alertmanager/actions/runs/6737380881/job/18314694645?pr=3589

**What did you expect to see?**

I expected the test to pass on the CI when changes don't affect it.

**What did you see instead? Under which circumstances?**

https://github.com/prometheus/alertmanager/actions/runs/6737380881/job/18314694645?pr=3589

**Environment**

n/a - CI

**Comment by gotjosh** [comment]
All the assertions as part of these tests are super flaky

We already have https://github.com/prometheus/alertmanager/issues/3287

**Comment by grobinson-grafana** [comment]
Looking at this test, I'm not sure how this is expected to work? Peer 2 joins Peer 1 in a different goroutine:

```
go p2.Settle(context.Background(), 0*time.Second)
```

The test goroutine then calls:

```
require.Equal(t, 2, p1.ClusterSize())
```

which can happen before the Go runtime has even scheduled the goroutine that calls `Settle` - let alone the memberlist having settled. I think settle should be passed a context with a timeout, and then if it succeeds the test checks the cluster size, otherwise it fails.

**Comment by grobinson-grafana** [comment]
Ah! I think this test is missing `require.NoError(t, p2.WaitReady(context.Background()))` as per the other tests.

**Comment by gotjosh** [comment]
Thank you both for the effort! And in particular @alexweav for the fix.
