### ISSUE TITLE
Version 0.1.1 Linux amd64 binary is stripped?

### ISSUE THREAD

**Issue by mattbostock** [prometheus/alertmanager#373]
It appears that the version 0.1.1 binary downloaded from the GitHub releases page is stripped:

```bash
$ file alertmanager-0.1.1.linux-amd64/alertmanager
alertmanager-0.1.1.linux-amd64/alertmanager: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, stripped
```

...whereas the previous version was not.

```bash
$ file ./alertmanager-0.1.0.linux-amd64
./alertmanager-0.1.0.linux-amd64: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.24, not stripped
```

Looking at AlertManager's makefile it doesn't look like the `-s` or `-w` [linker flags](https://golang.org/cmd/link/) are being used.

My understanding is that stripping Go binaries is dangerous ([source](https://github.com/docker/docker/blob/2a95488f7843a773de2b541a47d9b971a635bfff/project/PACKAGERS.md#stripping-binaries), [source](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717172)).

**Comment by brian-brazil** [comment]
@sdurrheimer

**Comment by sdurrheimer** [comment]
Stripping with `-s` and `-w` ldflags is fine and the recommended way of stripping go binaries. Why would those ldflags exist if it break go binaries. What is not recommended is to use tool like `strip` command which are external of the golang tool set.

Anyway, we don't strip our binaries ([ldflags used with alertmanager](https://github.com/prometheus/alertmanager/blob/master/.promu.yml#L6-L11). We only do it for the darwin platforms, because without it we can't crossbuild for this platform ([source](https://github.com/prometheus/promu/blob/master/cmd/build.go#L127-L131)).

`0.1.0` and `0.1.1` happened before the new release process was merged. Maybe did @fabxc uses the `-s` ldflags when he was using the new release process locally on his machine.

**Comment by BBK-PiJ-2015-11** [comment]
> Stripping with -s and -w ldflags is fine and the recommended way of stripping go binaries. Why would those ldflags exist if it break go binaries.

Indeed; I mentioned those flags in case the `file` command considered an executable to be 'stripped' if those linker flags were used.

Is that the case here, i.e. the file is considered 'stripped' due to ldflags rather than use of the `strip` command?

**Comment by mattbostock** [comment]
> Stripping with -s and -w ldflags is fine and the recommended way of stripping go binaries. Why would those ldflags exist if it break go binaries.

Indeed; I mentioned those flags in case the file command considered an executable to be 'stripped' if those linker flags were used.

Is that the case here, i.e. the file is considered 'stripped' due to ldflags rather than use of the strip command?

**Comment by sdurrheimer** [comment]
Yep, we don't use the `strip` command.

I just did the test, with the `-s` ldflags, the binary is considered 'stripped'.

**Comment by mattbostock** [comment]
That's useful to know. Thanks for checking, much appreciated.

Since we're stripping the binaries safely, I'll close this issue.
