### ISSUE TITLE
Dockerfile: don’t run alertmanager as root

### ISSUE THREAD

**Issue by stapelberg** [prometheus/alertmanager#39]
I don’t see a reason for alertmanager to run as root, not even in a docker container. Could we change it so that it runs as nobody/nogroup instead?

**Comment by juliusv** [comment]
Totally. @discordianfish the same would be true for all/most of the other Docker containers probably?

**Comment by discordianfish** [comment]
Yes, those things shouldn't run as root. I was just too lazy to change it. I can look into this once I find some time, until then PRs are welcome :)

**Comment by stapelberg** [comment]
Doing the change itself is easy, and I would have sent a pull request, but first I’d like to know what your migration strategy is:

If we just added `USER nobody` to the Dockerfile, alertmanager will not be able to write to existing volumes anymore, because these volumes are owned by root. Are you okay with breaking every of your Docker users?

If not, how could we solve this in a way that doesn’t break? One way I can think of is doing the privilege dropping inside alertmanager (not sure if that’s feasible in Go), or at least chowning the files inside alertmanager so that we can do a two-step migration.

What do you think?

**Comment by juliusv** [comment]
Well, we do have a big bold "still experimental!" warning at the top of the alertmanager `README.md`, and in general, Prometheus is still in 0.x-land, meaning we can still break things when necessary or when it wouldn't be worth it to spend a huge amount of energy to provide a migration path. This might be such a case, especially because alertmanager keeps little persistent state.

But once we want to do that with the Prometheus server itself, we should probably be a bit more careful. I think it's probably not worth dealing with privilege dropping inside Prometheus itself, but maybe something in the startup path could do a chown as you suggested (and then run Prometheus as the new user). Then we should announce on the mailing list that this two-step migration is happening, or otherwise people will accidentally skip over that intermediary image and still have breakage (people will still do that anyways, but hey).

**Comment by discordianfish** [comment]
I think it's okay that it breaks. The only reasonable use for a volume in this case is to store the config, so alertmanager might not be able to read it after the change but that breaks in a clear and easy to understand way
