### ISSUE TITLE
UI: Regexp checkbox not selectable in Firefox

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#436]
In Firefox, when you click the regexp checkbox in the silence form, nothing happens.

**Comment by beorn7** [comment]
@astera here you can check the progress on the issue discussed.

**Comment by fabxc** [comment]
I know this is not a solution, but does tab-ing and hitting space work in the meantime?

**Comment by beorn7** [comment]
While the checkbox seems to be in the tab cycle, it is neither highlighted in any way while focused, nor does it react to hitting space.

**Comment by grobie** [comment]
@beorn7 Can you test again? Works for me in Firefox.

**Comment by astera** [comment]
@grobie What happens (on my machine) currently is that in Firefox, you can edit a silence, and clicking the `Regex` checkbox makes it appear checked; however on hitting `UPDATE` to save any changes made, the setting is 'forgotten', and the value that should be a regular expression is assigned with an `=` instead of `=~`.

**Comment by grobie** [comment]
I can confirm, even with Chrome. I'll fix it today and release v0.4.2.

**Comment by grobie** [comment]
Will be released with v0.4.2.

**Comment by RRAlex** [comment]
This seems to still be a problem in latest (0.5.1)

**Comment by brancz** [comment]
@RRAlex it seems to be a new problem tracked here: https://github.com/prometheus/alertmanager/issues/565
