### ISSUE TITLE
Use unique names for asset files

### ISSUE THREAD

**Issue by grobie** [prometheus/alertmanager#478]
At the moment asset files will be cached and users need to hard refresh the site a couple of times to really get the current asset files. Use unique file names in builds.

@stuartnelson3

**Comment by stuartnelson3** [comment]
I believe you when you say this is happening, but I'm not sure why. We are using `http.ServeContent`, which uses the modtime for the generated assets to compare against the `If-Modified-Since` header that is sent by the browser (by chrome on my version of OS X, at least).

https://github.com/prometheus/alertmanager/blob/master/ui/web.go#L44
example of generated modTime: https://github.com/prometheus/alertmanager/blob/master/ui/bindata.go#L447

https://golang.org/pkg/net/http/#ServeContent

https://golang.org/src/net/http/fs.go?#L151

It seems like it should never be responding with a 302 since we don't set an ETag on the request ...

**Comment by mxinden** [comment]
With the new UI we deactivate any kind of browser caching. I know this is not a perfect solution, but so far we have no performance complaints. I will close here. @grobie Please reopen if you are facing similar issues with current Alertmanager versions or if you feel like the performance of the UI should be improved via caching.
