### ISSUE TITLE
Alertmanager .Value not updated for subsequent reports

### ISSUE THREAD

**Issue by LuboVarga** [prometheus/alertmanager#579]
Is that intention, that if alert manager reports some problem, its value in mail is correct only for first report (I have custom email template and I use **.Value** to access value)? All subsequent reports (**repeat_interval** I have set to 3 hours), have same value and not updated one (actual at time of mail sending).

**Comment by mxinden** [comment]
@LuboVarga Sorry for not following up here. I will close here due to inactivity. In case this issue still persists for you, please reopen the issue with a more in depth description of your problem and a detailed reproduction description.

**Comment by matejzero** [comment]
I'm not the original owner, but I'm also hitting this problem. I get an alert with the initial value, but that value is not being updated in Alertmanager, although I see different values in Prometheus UI.

My setup is really simple with mostly default settings, since I'm just evaluating Prometheus.
Prometheus: 2.2.0
Alertmanager: 0.14.0

If you need any other information, I would be happy to get them.

Prometheus:
![prometheus](https://user-images.githubusercontent.com/4689252/37403471-43a922aa-278f-11e8-9e0c-0355dc06b712.png)

![screen shot 2018-03-14 at 13 55 52](https://user-images.githubusercontent.com/4689252/37403539-73debebc-278f-11e8-9f37-68212729e5d4.png)

Alertmanager:
![alertmanager](https://user-images.githubusercontent.com/4689252/37403489-49eff602-278f-11e8-807e-11c33971afa9.png)
