### ISSUE TITLE
Metric for config consistency

### ISSUE THREAD

**Issue by brancz** [prometheus/alertmanager#596]
In a highly available setup of the Alertmanager each instance has to be configured in the same way for the cluster to be working as expected, therefore it is a problem if any of the loaded configs differ.

The easiest way to figure out an inconsistency of such a case would be to hash the currently loaded config and expose the hash as a metric (gauge). Then we can alert on the hashes to be equal.

Thoughts?

@fabxc @brian-brazil @alexsomesan

**Comment by brian-brazil** [comment]
Makes sense.

**Comment by alexsomesan** [comment]
I like the idea. Let's try it out.

**Comment by brian-brazil** [comment]
We've got 54 bits to play with, so a 32bit hash should do it.

**Comment by brancz** [comment]
What do you think of a CRC32?

**Comment by brian-brazil** [comment]
Either that or take the lower bits of an md5.

**Comment by fabxc** [comment]
Why not just make the value 1 and put the hash into a label like `alertmanager_config_hash{hash="abcdef"} 1`

Alert on:
`count(sum by(hash) (alertmanager_config_hash)) > 1`

**Comment by brian-brazil** [comment]
That creates unnecessary timeseries and breaks with current staleness handling. min+max or count_values can deal with it as a value.

**Comment by tjsampson** [comment]
I know this is a pretty old issue, but I am curious what query you all have come up with to monitor/observe this metric? We have a similar metric in our proxy layer where we are building config dynamically (event based) and we have seen config sync issues, where 1 pod instance has 1 value, and the other pod instance has a different hash value. So, we created a similar metric where we hash the config and expose it as a float64 value. The name of our metric is `proxy_config_hash`

This is what we have come up with so far:
```
 count_values("config_hash", proxy_config_hash{namespace=~"$namespace"}) BY (namespace) / ON(namespace) GROUP_LEFT() label_replace(max(kube_deployment_spec_replicas{namespace="$namespace"}) by (namespace), "service", "$1", "name", "(.*)") !=1
```

We want to make sure that all of the replicas in the namespace have the same config_hash value. And if there is a difference, show the time series and how long they were out of sync (and alert if config sync is too long):
![Screenshot 2024-06-15 at 6 43 46 AM](https://github.com/prometheus/alertmanager/assets/8485836/348f305d-c7e6-4dde-a996-56544d4c8eb4)


Do you see any issues with that query? Are you all doing something similar? Thanks in advance for any help/pointers.

**Comment by tjsampson** [comment]
> Do you see any issues with that query? Are you all doing something similar? Thanks in advance for any help/pointers.

There's definitely some improvements we need to make with this query, but I'm not entirely sure how to make it behave the way I'd like. For example, there's a config sync "issue" in that chart above that shows a span of over 3 hours where the config was out of sync (value `6481103516507458000`), but when I look at the logs, I am only seeing a difference of .001 seconds. Which is pretty typical/standard, since the process is event based (not every pod receives and processes the event at the exact same time, which is fine and even expected).

![Screenshot 2024-06-15 at 8 03 49 AM](https://github.com/prometheus/alertmanager/assets/8485836/12eabb0a-4243-4c44-9184-a5f308c75141)

Make me wonder if the scraping nature of prom and timing in general is a good approach to detecting these types of drift. We may just have to rely on logs, since we have the timestamps to play with and we are getting those in a continuous stream. All of our logs are telling a pretty accurate story. Most of the syncs happen simultaneously, or even within milli/microseconds of each other.

**Comment by tjsampson** [comment]
I need to test this query, but instead of division and expecting 1, maybe it's better to just compare the counts?

```
label_replace(max(kube_deployment_spec_replicas{namespace="$namespace"}) by (namespace), "service", "$1", "name", "(.*)") != count_values("config_hash", proxy_config_hash{namespace=~"$namespace"}) BY (namespace)
```

I'm going to write some test code that forces one pod to not pickup the sync correctly every 15 mins with a modulus operator (even/odd), to force an invalid sync from hh:15 (odd) - hh:30, valid sync from hh:30 (even) - hh:45, invalid from hh:45 (odd)-hh:00, valid from hh:00 (even) - hh:15, repeat....stay tuned.
