### ISSUE TITLE
Improve debuggability of HA and mesh

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/alertmanager#625]
If HA isn't working correctly there's very little to help you debug it.

It would be useful to have metrics showing the amount of data the mesh is handling, how many notifications were inhibited by it, how big the mesh is etc.

Log wise, info logs when the mesh is joined and its members change would be useful. Debug logs on how the HA features affect notifications would help.

Information on the status page relating to the mesh would be helpful.

**Comment by fabxc** [comment]
Did you hit a debugging case or is this a general issue?

**Comment by brian-brazil** [comment]
I'm currently helping a user debug an issue and everything looks to be setup correctly thus far, however there are duplicate notifications.

**Comment by Rudd-O** [comment]
I have HA problems too.  Silences set on one of the nodes propagate to one other node, but not to the third.  This is causing alerts to be sent when we don't want them sent.  Nothing in the debug logs to fix or even to track down the issue either.

**Comment by stuartnelson3** [comment]
@Rudd-O can you write an email to the prometheus-users google group with the following:

- Describing your situation
- Your command line invocation for the 3 nodes
- Basic machine information

It might just be a configuration mistake, and if it's an actual bug then we can write it up as an separate issue.

**Comment by Rudd-O** [comment]
On 03/30/2017 10:53 AM, stuart nelson wrote:
>
> @Rudd-O <https://github.com/Rudd-O> can you write an email to the
> prometheus-users google group with the following:
>
>   * Describing your situation
>   * Your command line invocation for the 3 nodes
>   * Basic machine information
>

I'm using the latest Docker container release of alertmanager.  I will
give you the command lines tomorrow as I am not at work right now. 
Basically, if I set a silence in one of my alertmanagers, it propagates
to one other, but the third doesn't get it.  Which one propagates to
which other one is really random.  I am confident this isn't a
configuration mistake.

I perused the source code and I do not see any logging statements that
could signal what the health of the mesh really is, not even in debug mode.

-- 
    Rudd-O
    http://rudd-o.com/

**Comment by stuartnelson3** [comment]
>Can you write an email to the prometheus-users google group...

**Comment by aecolley** [comment]
At the risk of metooing, I also have a great need for mesh metrics. I have three long-running alertmanagers in a mesh, and today I found that one of them had lost its connections to the other two. Nothing appears in the log and there are no metrics which I could use to drive an alert for the condition. I found the problem only because an alert notification was sent which should have been silenced.

To forestall a repeat of the earlier comments from March, let me make clear that the alertmanagers have TCP connections to each other on the mesh port, but at some point (possibly after a month of uptime) connections get dropped and are not re-established.

**Comment by simonpasquier** [comment]
This issue relates to the old mesh library which has been since replaced so I'm going to close it.
* The latest AlertManager release includes additional cluster metrics that should ease monitoring and troubleshooting.
* The status page of the UI includes information about the cluster.
* Debug logs show when peers are joining and leaving the cluster.
