### ISSUE TITLE
Make metrics usable when instantiating multiple Collectors of the same type

### ISSUE THREAD

**Issue by juliusv** [prometheus/alertmanager#646]
In [Weaveworks' multi-tenant Alertmanager](https://github.com/weaveworks/cortex/blob/master/alertmanager/multitenant.go), we reuse packages from Alertmanager and instantiate a full chain of alerts DB, silences, nflog, etc. for each user (in the same process). However, some of those components implement the `prometheus.Collector` interface to do metrics, which starts breaking down when you try to register multiple collector instances of the same type. Unfortunately, wrapping each collector instance to add a distinguishing label (tenant ID) doesn't work, as the necessary fields in the `Descs` etc. are not exported.

Some ideas: If one wanted to fan out metrics by some per-instance label (like the tenant ID), then perhaps one could pass in const labels into the collector to be applied to all of its metrics. On the other hand, if one wanted to *share* just one set of metrics for all users, one could perhaps pass in a metrics struct to be used? That would not work sensibly for gauges however.

Any thoughts on how to cope with this? I've hit the issue specifically with the AM packages, but it's also an interesting general question.

/cc @fabxc @beorn7

**Comment by beorn7** [comment]
If you want to _share_ metrics, you have to share metrics, I'd say. You don't even need to pass around the metric instances themselves, see the example for https://godoc.org/github.com/prometheus/client_golang/prometheus#AlreadyRegisteredError , i.e. it would be enough to pass around the `Registerer` (or use the global default registry). The pattern of implementing `Collector` doesn't work, indeed, and I'd say rightfully so.

For the discussion around how to wrap/curry with labels (or perhaps even a naming prefix AKA poor man's namespacing), see https://github.com/prometheus/client_golang/issues/269 .

**Comment by brian-brazil** [comment]
One thing to consider is that if the labels are different then the name should also be different, as it's not the same metric. Having everyone put their own prefix on names however breaks horizontal monitoring.

**Comment by juliusv** [comment]
@beorn7 Sharing metrics like that would require global metrics though, which I'd like to avoid. Thus the idea of being able to pass in a shared metrics struct if one wanted the shared use case. Still, it wouldn't work for gauges that pertain to e.g. per-collector queue lengths.

@brian-brazil Why should the metric name be different if only the tenant label is different, but the label names are always the same?

As a client library solution to the per-collector label values use case seems far off, I wouldn't want to wait for that. So I'm just wondering whether either the "pass in a struct" approach (for shared metrics) or the "pass in const labels" approach (for per-tenant metrics) would be ok in the Alertmanager components. Or maybe there's another smart thing one could do right now. But my guess is that @fabxc wouldn't like global metrics at least.

Right now I'd lean towards being able to pass in const labels. It doesn't scale for huge numbers of users, but it works with gauges.

**Comment by brian-brazil** [comment]
> @brian-brazil Why should the metric name be different if only the tenant label is different, but the label names are always the same?

It wouldn't. Adding a tenant label to a metric that doesn't have one makes it a different metric.

**Comment by beorn7** [comment]
@juliusv Yes, it wouldn't work for "shared" Gauges (how should anything work for that...). But it would not require any global metrics.

In any case, if you want to solve Gauges properly, you need to do the aggregation on the Prometheus level and thus have a tenant label on them (as you said). (Or you needed to implement aggregation logic in your code before even hitting the Prometheus library...)

**Comment by juliusv** [comment]
@brian-brazil 
> It wouldn't. Adding a tenant label to a metric that doesn't have one makes it a different metric.

As long as I can ensure that in my environment, I only ever have the same label names on a given metric, this would work fine. But of course, from a purist perspective one might still object, because people could abuse it.

@beorn7 Yep, thus I would prefer the possibility to inject const labels into the AM collectors as a first step.

**Comment by brian-brazil** [comment]
> But of course, from a purist perspective one might still object, because people could abuse it.

We've seen enough related abuses of labels (e.g. putting a version number label on everything) that it seems fairly likely.

**Comment by juliusv** [comment]
> We've seen enough related abuses of labels (e.g. putting a version number label on everything) that it seems fairly likely.

I wouldn't suggest this as a general pattern just yet, but just as a special-case option in the internal AM packages to allow me to reuse them in a multi-tenant AM. A client library update is probably going to take a long time, so the question is whether it's ok for me to add this as a stop-gap solution here in the interim. The alternative would be forking those packages or living without metrics.

**Comment by beorn7** [comment]
I guess the custodians of the AM code ( @fabxc @stuartnelson3 ) should decide if it's OK to have this "special purpose code" in there.

In different news, we could try to expedite the decision if we want "curried" Registerers in client_golang. I deferred the decision to v0.10, because it kind of depends on a breaking change in the `Desc` implementation. However, we could implement it right now inside the same package as the `Desc` implementation because we can manipulate the internals of a `Desc` there… Perhaps I can spike this during the weekend.

**Comment by juliusv** [comment]
> Perhaps I can spike this during the weekend.

@beorn7 That'd be a cool alternative as well of course :)

**Comment by fabxc** [comment]
There's no way around passing in const labels right now. Was at the same place elsewhere and also ran into a wall when not being able to wrap the registry with the required logic due to metric descs not exposing required fields.

I do not agree with allowing random components to now have additional arguments for const labels because some company needed it. It is arbitrary, sets a bad example, and will with 99% guarantee lead to similar "hot fixes" being slapped all over the place without ever being taken care of as technical debt.
"As a first step" does not work at all based on past experience.

Adding this to the client library is not a one-liner but honestly, not hard either.  It's about exposing same fields and/or providing a wrapper around `Registry` or similar. I'd encourage the latter as it benefits the wider eco system.
This is just something where weaveworks will have to contribute some upstream efforts that are not directly driving their internal needs, sorry – or fork, however they prefer.

On other discussions: I don't see why prefixing metric names is in any way sane here. The metric name encodes the semantic meaning of the value, i.e. what is measured and how. Partitioning the metric by one further dimension does not affect the semantic meaning.

**Comment by brian-brazil** [comment]
> I do not agree with allowing random components to now have additional arguments for const labels because some company needed it.

The way I've seen this play out previously is that things will start out with the per-file metrics (and metrics usually stay that way indefinitely). At some point a particular module/metric might find a new way of being used, in which case it gets a rewrite to use (only) the new metric or some way to pass in some form of "shard" identification in the constructor.

What that'd imply here would be a "tenant" label that could be passed in to the relevant bit of the AM code, which'd then be used with the standard per-file metric.

I'd never seen it that a given bit of code needs to be broken out in more than one way (i.e. different labelnames don't happen IME).

> Partitioning the metric by one further dimension does not affect the semantic meaning.

It does, as it requires different label handling in expressions. Changing the label names on a metric is always a breaking change.

**Comment by beorn7** [comment]
I like the idea of "curried Registerers" more and more. Weekend was just cramped. Once I have a few idle cycles, I'm happy to give it a try. Should be relatively easy.

> On other discussions: I don't see why prefixing metric names is in any way sane here. The metric name encodes the semantic meaning of the value, i.e. what is measured and how. Partitioning the metric by one further dimension does not affect the semantic meaning.

In this concrete context (multi-tenant), prefixing wouldn't really solve the use-case. In general, a Registerer curried with a prefix would take the role of namespace/subsystem, but this time in the proper way.

Could look like:
```Go
curriedReg := prometheus.DefaultRegisterer.WithPrefix("alertmanager").With(prometheus.Labels{"tenant": "foo"})
```

**Comment by brian-brazil** [comment]
> In general, a Registerer curried with a prefix would take the role of namespace/subsystem, but this time in the proper way.

The is a different use case. Namespace is about the library name, so e.g. all grpc metrics would always have a grpc_ metric no matter which application they're inside. If users started prefixing all metrics with their application name that'd be bad, as that makes horizontal monitoring challenging and would likely result in other anti-patterns.

What we're talking about here is where labels are being added due to sharding of some form being added to something that's normally unsharded, which is fairly rare.

**Comment by juliusv** [comment]
@fabxc Yes, totally fair comment. Seems like this won't be solved here directly, so closing.

@beorn7 Thanks, that would be useful to have!

**Comment by fabxc** [comment]
> curriedReg := prometheus.DefaultRegisterer.WithPrefix("alertmanager").With(prometheus.Labels{"tenant": "foo"})

That looks pretty much like what the interface should be 👍
