### ISSUE TITLE
Feature request: add histogram metric for time alert was firing

### ISSUE THREAD

**Issue by mattbostock** [prometheus/alertmanager#653]
So that you can detect flapping alerts and determine how actionable an alert is, it would be good if Alertmanager exposed a histogram metric for the amount of time that an alert was firing.

Such a metric could have high cardinality (hundreds of alert names with a few buckets each could result in a lot of metrics), so we might want to disable it by default.

Or perhaps there's a better way of tracking this, e.g. by reporting alerts to Elasticsearch and analysing the data after the fact.

**Comment by brian-brazil** [comment]
That's not a metric about the alertmanager, so it doesn't belong on /metrics.

This is something to be be analysed in another tool after the fact I think.

**Comment by mattbostock** [comment]
I'll look at doing this with an Elasticsearch script.

**Comment by juliusv** [comment]
@mattbostock Note that Prometheus stores pending + firing alerts in an `ALERTS` metric with the alertname and other alert labels as labels. When the alert goes into `firing`, the corresponding `firing` time series for it first appears with value `1`, and when an alert is resolved, a final `0` sample is written out for it. So you could for example do something like this to find the alerts that are going on and off the most over the last week:

```
sort_desc(changes(ALERTS{alertstate=`firing`}[1w]))
```

Or finding the alerts which were generally most active in the last week:

```
sort_desc(sum_over_time(ALERTS{alertstate=`firing`}[1w]))
```

You can't `avg_over_time()` because the time series disappear when an alert for a specific label combination stops firing.

**Comment by mattbostock** [comment]
Thanks @juliusv, `changes()` is a good start.
