### ISSUE TITLE
Silence alarm from email template

### ISSUE THREAD

**Issue by raypettersen** [prometheus/alertmanager#722]
Just an idea I'd like to share. Today we have one link in the default email template, "source". I would like to have another link called "silence", which populates the necessary items in the alertmanager-gui for silencing that particular alarm.

**Comment by mxinden** [comment]
With the new UI you can achieve this with two instead of one click. Once you clicked on the `source` url, you can choose the `Silence`, which will forward you to a populated silence form.

I will close here. Feel free to reopen, if you would like us to look further into the one-click solution. Thanks for sharing your thoughts!
