### ISSUE TITLE
Splitting up alertmamager config

### ISSUE THREAD

**Issue by Alwaysc0d3** [prometheus/alertmanager#870]
Is it possible to split up the alermanager config / route rules? 

We arr currently havind a whole bunch of alerting and routing rules, in a more perfect situation you should be able to split this up. 

Just like there's done for the alerting rules of premotheus. 

Can this be done by the templating function (which isn't well documented, causing the confusion).

I would like to hear from you guys,
By the way... if this isnt impemented yet, coyld you guys create something like that? I assume the most of theje code could borrowed from the prometheus alerting code :-)

**Comment by stuartnelson3** [comment]
The file cannot be split up at this time. You could use a configuration management system to merge the two files together at deploy time, though.

I would suggest using config management instead of implementing this in a pull request. I'll leave the issue open in case this is something more people would like to see.

**Comment by wombledmaize** [comment]
Thanks for the reply. I did some research and wasn't even aware of the option you proposed. That's working for me. Thanks. 

The feature would be nice, for people without an config management system.
@stuartnelson3 thanks!

**Comment by brian-brazil** [comment]
Prometheus presumes that you have configuration management, it's out of scope for us to duplicate that functionality.
