### ISSUE TITLE
New receiver for AWS API Gateway

### ISSUE THREAD

**Issue by geethika-guruge** [prometheus/alertmanager#888]
We have a use case to trigger an AWS lambda (exposed via AWS API Gateway) upon an alert. As we would need to pass the API Key in `x-api-key` header for authentication, initially we looked at [issue #739 ](https://github.com/prometheus/alertmanager/issues/739). But realised that a new receiver for AWS API Gateway would be a better fit. 

Any thoughts?

**Comment by brian-brazil** [comment]
Per our security model (https://prometheus.io/docs/operating/security/) putting secrets in random fields is not supported. I'd recommend writing a webhook receiver.

**Comment by geethika-guruge** [comment]
We recently started using Prometheus and have limited knowledge on the source
> writing a webhook receiver

did you mean something like `<hipchat_config>`? or is there a way to extend the existing `webhook receiver`

Thanks
.

**Comment by brian-brazil** [comment]
The webhook receiver supports sending JSON to any endpoint you like over HTTP. You can write a small program that takes these in, and talks to lamda for you. https://prometheus.io/docs/alerting/configuration/#<webhook_config> has a bit more information.

**Comment by geethika-guruge** [comment]
We looked at that option originally, but felt it would be tidier (and less moving parts) if we can integrate that piece of functionality to prometheus itself. 
Thanks

**Comment by mxinden** [comment]
@geethika-guruge please understand that it is very difficult to maintain all of these integrations. That's why we are trying to keep the integration set of both Alertmanager and Prometheus to a level, where we can still assure stability without being overwhelmed by the amount of integrations we have to maintain.

I am closing here. Please reopen if you are facing any further issues. In addition there is also the https://groups.google.com/forum/#!forum/prometheus-users were you can find a lot of help.
