### ISSUE TITLE
Alertmanager integration with ServiceNow

### ISSUE THREAD

**Issue by prasenforu** [prometheus/alertmanager#931]
ServiceNow is one of popular services management tool which does ticketing, problem management, change management etc.

Is it possible to integrate alertmanager with ServiceNow for tickets purpose, when there was any problems in alert rules, it wil trigger servicesnow and create ticket.

**Comment by stuartnelson3** [comment]
Thank you for the request!

Our webhook receiver is probably the fastest way to get something working that fits your needs: https://prometheus.io/docs/alerting/configuration/#<webhook_config>

We will have a look and evaluate the request, thanks!

**Comment by Murryy79** [comment]
I am looking for ServiceNow integration as well.
is there a working configurations someone has figured out? would be helpful.

I have heard sending emails to ServiceNow can convert into tickets.

**Comment by prasenforu** [comment]
Best solution using call webhook as @stuartnelson3 mentioned.

**Comment by DonMartin76** [comment]
We are also looking at doing some kind of integration to ServiceNow, and it might possibly be useful for others as well. Currently, the requirements would be something like this:

* For some alerts, e.g. of some specific severity, open a ServiceNow ticket (which might trigger an "Outage" in ServiceNow)
* If the alerts go away, automatically update the ServiceNow ticket with the new state, so that the Outage is automatically taken out again

Difficult things are among the following:

* How to persist which alerts went into which ticket, so that tickets aren't created multiple times
* How to make the adapter (that's what it would be) resilient enough to survive a rescheduling (persistent storage?)

**Comment by jnovack** [comment]
So, I'm here because I came looking for this same thing.  Unfortunately, the ServiceNow REST Incoming API expects the data in a specific format (bummer, not the format you are sending), unless you are willing to write your own REST Client API, which is "good enough" for those with general requirements.

I can help a project dev with getting a ServiceNow instance set up and guidance and best practices on getting the data to the right places if he or she wants to spend to time with me. 

I am super n00b in Go.  I'm familiar with other languages, and it does not seem that complicated, just... different.

One of the requirements for function is that you will be returned a `sys_id` which your **resolve** message should use to properly close the ticket.   Here's where I'm completely confused looking at the code at how this could be done as currently all the alerts are "fire-and-forget" to notification services.

```bash
curl "https://instancename.service-now.com/api/now/table/incident" \
--request POST \
--header "Accept:application/json" \
--header "Content-Type:application/json" \
--data "{}" \
--user 'user':'password'
```

Where `{}` is:
```json
{
  "short_description": "{{ .Annotations.summary }}",
  "description": "{{ .Annotations.description }}",
  "state": 1
}
```

The **resolve** would need to be a `PUT` with the `sys_id` number returned from your earlier **firing** to properly close the ticket.

```json
{
  "sys_id": "abcdef1234567890",
  "state": 6
}
```

There's tons of fields which can translate 1-to-1 as optional labels by default:
* `category`
* `subcategory`
* `impact`
* `urgency`
* `assignment_group`
* `assigned_to`

The YAMLConfig can hold optional defaults for all alerts:
* `caller_id`
* `contact_type`

I'm willing to help assist a dev, we can discord/slack/hangouts/email!  Help me, help you!  I'll do the documentation!!

Pros:
* You +1 AlertManager's integrations
* I +1 my Go-fu
* We both make a new friend!

Don't delay, sign up today!

**Comment by jdtagu** [comment]
Hello,
Was there any outcome of the above integration with service now?
I am interested.
Thanks

**Comment by kenmaglio** [comment]
@TyAbbott I'm going to attempt to do the same thing here, as we have a need to push alerts into SNOW from AlertManager.

**Comment by t451772** [comment]
@TyAbbott There is still interest for this, as I need to do the same thing. Is the code you posted the best place to start? I looked through your projects and I didn't find any updates. If this has been integrated into a more official feature I would also be interested in that. For anyone still looking there is also the snogo project which attempts the same goals and that can be found here:
https://github.com/HealthPartners/snogo

**Comment by thart20** [comment]
@t451772 I've been looking into doing the same thing, going off of @TyAbbott I've made something similar that can also update existing incidents or close them when the alert switches to resolves:

`(function process(/*RESTAPIRequest*/ request, /*RESTAPIResponse*/ response) {

    var requestBody = request.body;
	var requestData = requestBody.data; // variable holds JSON data
	
	var status = requestData.status;
	var summary = requestData.alerts[0].labels.summary;
	var description = requestData.alerts[0].labels.description; // creates a variable matching a label you give on your alert
	var inc = new GlideRecord('incident'); // accesses the incident table
	var incidentExists = false;
	
		inc.addQuery('short_description', summary); // searchs the incident table for any incident description that matches the alert summary
		inc.query();
		if (inc.hasNext()) {
			incidentExists = true; // if a match is found, the incident Exists var becomes true
            inc.next();
        } else {
		inc.initialize(); 
		}
		
	if (incidentExists) { 
	response.setStatus(200);
		if (status == "firing") { // if the incident exists, the incident status is set to in in progress and comments are added
			inc.short_description = summary; 
			inc.comments = description; 
			inc.state = 2;
			inc.update(); // Updates an existing incident
		}
		else if (status == "resolved") { // If the incident exists, but the status of the alert is now resolved, the incident is closed.
			inc.short_description = summary; 
			inc.comments = "The Prometheus Alert is no longer occuring, the issue has been resolved."; 
			inc.state = 6;
			inc.update();
		}

			
		
	} else { // if no existing incident is found, it created a brand new one
		inc.short_description = summary; 
		inc.comments = description; 
		inc.caller_id = "1111111"; //Can match a label if you prefer, or set one manually.
		inc.state = 1;
		//labels are accessed in the alerts. Will then look through the JSON payload and match any labels to incident fields. 
		inc.urgency = requestData.alerts[0].labels.severity;
		inc.location = requestData.alerts[0].labels.location;
		inc.category = requestData.alerts[0].labels.category;
		inc.subcategory = requestData.alerts[0].labels.subcategory;

                inc.insert();  // Creates a new incident
		
	}

})(request, response);`

As long as your labels match the fields Servicenow uses, it should work. I've found that using annotations on your alerts doesn't work so well, Snow seems to have some problems with it if more than one alert is firing and creating incidents..

**Comment by louisfelix** [comment]
For the record, here is a generic webhook that integrates ServiceNow to AlertManager:
https://github.com/FXinnovation/alertmanager-webhook-servicenow 

It supports alerts grouping, updating an existing incident based on the group key, dynamic fields configurations and GO templating on fields values (from alert's annotations and labels).

**Comment by simonpasquier** [comment]
@louisfelix you can add it to this [list](https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver) if you wish. Just open a PR for this [file](https://github.com/prometheus/docs/blob/master/content/docs/operating/integrations.md).

**Comment by louisfelix** [comment]
> @louisfelix you can add it to this [list](https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver) if you wish. Just open a PR for this [file](https://github.com/prometheus/docs/blob/master/content/docs/operating/integrations.md).

Thanks @simonpasquier ! [PR](https://github.com/prometheus/docs/pull/1473) created.

**Comment by niranjanreddy48** [comment]
Can this be mapped to event table(em_event) of servicenow instead of incident table? i want the alerts to go to event table of servicenow and then the event rules trigger and process the alerts.

**Comment by louisfelix** [comment]
> 
> 
> Can this be mapped to event table(em_event) of servicenow instead of incident table? i want the alerts to go to event table of servicenow and then the event rules trigger and process the alerts.

Hi, no, the mentioned [webhook](https://github.com/FXinnovation/alertmanager-webhook-servicenow) only supports the incident table.

**Comment by ashishkumar02** [comment]
@prab2014 DId you get any solution?

**Comment by s-phalke** [comment]
If anyone needs this, feel free to use https://github.com/s-phalke/alertmanager-webhook-servicenow.

Credit: https://github.com/FXinnovation/alertmanager-webhook-servicenow and updated with fixes.
