### ISSUE TITLE
[FR] Configurable maximum silence durations

### ISSUE THREAD

**Issue by RichiH** [prometheus/alertmanager#941]
We want to force periodic review of silences. Being able to set a maximum duration for silences being newly created would solve that.

**Comment by brian-brazil** [comment]
I'm against having such a feature. It'll be abused by higher ups setting it too low, forcing unnecessary toil on those who are oncall. If you want to force a periodic review of silences, that's an internal process issue for the organisation.

**Comment by RichiH** [comment]
If the PHB wants to force people down that path, how is the availability of such a setting going to enable or stop them?

**Comment by brian-brazil** [comment]
They're only enabled if we provide the feature, thus us not providing that feature provides discouragement for those that might think this is a good idea.

Merely having such a setting would prompt discussions around what it should be set to, and it's not at all difficult to imagine one team who likes burning themselves out setting it too low for other teams who have a real need for effectively indefinite silences (e.g. 1 hour limit due to that being in an SLA somewhere vs. an active-passive system with manual failover every few months where you need to silence the passive part).

In my opinion if an organisation really wants this, they can implement it via a private fork or a proxy.

**Comment by caarlos0** [comment]
So, this can be closed I guess?
