### ISSUE TITLE
[FR] Add metrics about silences

### ISSUE THREAD

**Issue by RichiH** [prometheus/alertmanager#944]
I would be interested to do stats over silences; and I would obviously like to do that via Prometheus. My main goal is to look at the durations of silences vs people/teams which created them.

**Comment by brian-brazil** [comment]
That is information about data inside the alertmanager, rather than information about the alertmanager's performance. Thus this doesn't belong on /metrics, in the same way we don't expose firing alerts on /metrics.

I'd suggest a separate tool to pull this from the API, as I can imagine this being very organisation specific. The alertmanager has no notion of teams for example.

**Comment by RichiH** [comment]
So a split like for snmp_exporter makes sense.

We do ingest the alerts and silences with our tools, but for the use case of "do analysis and graphs on metric data", I don't want to _not_ use Prometheus.

Teams are a label; my use case is org-specific, but the notion of using labels to slice and dice data is not.

**Comment by caarlos0** [comment]
close?
