### ISSUE TITLE
value_re in filter rules silently adds "^" and "$"

### ISSUE THREAD

**Issue by miekg** [prometheus/alertmanager#99]
This is pretty non-obvious:

https://github.com/prometheus/alertmanager/blob/master/manager/filter.go#L39

At least it should be mentioned in the docs are removed entirely and let users fully specify the regexp themselves.

**Comment by juliusv** [comment]
@miekg I'd actually love for this behavior in Alertmanager to be the default for all regexes in the Prometheus server as well (full string match instead of substring match). It would be a breaking change to the server, but maybe still worth it. Most of the times people want to match things like `4..` (HTTP status codes), `GET|POST`, etc., which in Prometheus currently have to be written as `^4..$`, `^(GET|POST)$`, and so on. But most people don't know this and write the (incorrect) former variants which work only by accident most of the time.

Are you saying this is non-obvious in general, or only because Prometheus currently does it the other way around than Alertmanager?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [alertmanager] value_re in filt..." ]
>@miekg I'd actually love for this behavior in Alertmanager to be the default
>for all regexes in the Prometheus server as well (full string match instead of
>substring match). It would be a breaking change to the server, but maybe still
>worth it. Most of the times people want to match things like `4..` (HTTP status
>codes), `GET|POST`, etc., which in Prometheus currently have to be written as
>`^4..$`, `^(GET|POST)$`, and so on. But most people don't know this and write
>the (incorrect) former variants which work only by accident most of the time.

I think it is more a documentation bug, then a bug in the code. I didn't read
about this in the alertmanagers docs (or glanced over it). Took me a while
to figure out why my '^blaa' regexp wasn't working properly...


/Miek

--
Miek Gieben

**Comment by brian-brazil** [comment]
We've settled on anchored regexes for labels, and the new alertmanager will not allow a regex to be specified here. Thus this is obsolete.
