### ISSUE TITLE
can i send alert to two receiver in one route ?

### ISSUE THREAD

**Issue by justlooks** [prometheus/alertmanager#997]
it seems alert manger can not recognize the following configuration

      routes:
      - match:
          severity: page
        receiver: ['slack_alert', 'email_alert']

**Comment by brian-brazil** [comment]
https://www.robustperception.io/sending-alert-notifications-to-multiple-destinations/

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
